#!/usr/bin/env python3
"""Pack re/stage1/font/font8.txt into a C array, 8 bytes (1 bpp) per glyph,
for ASCII $20-$5A. Characters the sheet leaves out stay blank.

    font8-pack.py font8.txt font8.c
"""
import sys

FIRST, LAST = 0x20, 0x5A


def main():
    src, out = sys.argv[1], sys.argv[2]
    glyphs, cur = {}, None
    for line in open(src):
        line = line.rstrip("\n")
        if not line or line.startswith("# "):
            continue
        if line.startswith("= "):
            name = line[2:]
            cur = " " if name == "sp" else name
            if len(cur) != 1 or not FIRST <= ord(cur) <= LAST or cur in glyphs:
                sys.exit(f"bad or repeated glyph {name!r}")
            glyphs[cur] = []
            continue
        if len(line) != 8 or set(line) - set("#."):
            sys.exit(f"{cur!r}: bad row {line!r}")
        glyphs[cur].append(sum(0x80 >> i for i, ch in enumerate(line) if ch == "#"))
    for ch, rows in glyphs.items():
        if len(rows) != 8:
            sys.exit(f"{ch!r}: {len(rows)} rows")
    data = []
    for code in range(FIRST, LAST + 1):
        data += glyphs.get(chr(code), [0] * 8)
    with open(out, "w") as f:
        f.write("/* generated by scripts/fpga/font8-pack.py from font/font8.txt */\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint8_t font8[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
